### PR TITLE
add --ping option to mcelog client

### PR DESCRIPTION
**Pull request by meow-watermelon**
This pull request introduces a new functionality to the `mcelog` command, an option enabling the execution of the `ping` command. This addition allows users to verify the readiness of the mcelog server before initiating other commands.

example:

```shell
#!/bin/bash

MCELOG_PING=$(mcelog --ping)

if [[ "$MCELOG_PING" == "pong" ]]
then
    echo "mcelog server is up"
else
    echo "mcelog server is not up"
fi
```

### CODE REVIEW

**Review by andikleen — CHANGES_REQUESTED** [review]
Instead of closing the connection use fflush to send the pong out, and don't exit the loop.
Also please add the new option to the manpage

**Comment by meow-watermelon** [comment]
Hi @andikleen thank you for the response. I have a dumb question here about the change request: if we just use `fflush` but not closing the connection, `mcelog` will hang and wait for more input from the socket right? could you give me some more insight about your comment? thank you.

**Comment by andikleen** [comment]
> Hi @andikleen thank you for the response. I have a dumb question here about the change request: if we just use `fflush` but not closing the connection, `mcelog` will hang and wait for more input from the socket right? could you give me some more insight about your comment? thank you.

Yes that's right. If the client wants to close the connection it can close it by itself. Or it could issue new commands, ping or something else, if it prefers.

**Comment by meow-watermelon** [comment]
Thank you for the response @andikleen. In this case, we just need `mcelog` prints out `pong` message then quit, because this option is used for checking if the mcelog server is alive or not. So shall I use `fflush` to flush `pong` out then close the fd and exit the loop?

**Comment by meow-watermelon** [comment]
This is the expected behavior:

```
# mcelog --ping
pong
#
```

**Comment by andikleen** [comment]
On Thu, Jan 04, 2024 at 11:27:48AM -0800, meow-watermelon wrote:
> Thank you for the response @andikleen. In this case, we just need mcelog prints
> out pong message then quit, because this option is used for checking if the
> mcelog server is alive or not. So shall I use fflush to flush pong out then
> close the fd and exit the loop?

The client should close the connection anyways, so why does the server
need to close it?

I would like the protocol supporting a use case where someone does
continuing pings through a single connection, possible intermixed with
other actions.

**Comment by meow-watermelon** [comment]
Thank you, @andikleen. I hope I have addressed your comment in my latest push.

**Comment by andikleen** [comment]
Thanks!

**Pull request merged**
