### PR TITLE
commented and consecutive page offlining for row-level failure implemente

### PR DESCRIPTION
**Pull request by AnkitSaxena114**

### CODE REVIEW

**Comment by ak-intel** [comment]
Thanks. You closed it because it needs more work?

A test case for the test suite would be good at least.

**Comment by AnkitSaxena114** [comment]
Hi!

I closed it because I accidentally tried to push something or create a
branch that I didn't mean to. This is my first time working on mcelog
related stuff! :)

I had a couple questions about the mcelog:

1) Is the mcelog repo supposed to be downloaded and installed for a given
server and from there, you can play around with the page offlining
features/make modifications?

2) I'm mostly interested in page offlining and coming up with an
optimal solution to error-prone DIMMS. If I were to come up with a more
sophisticated solution that 10CE/24 hours (which is the default threshold
for now), would modifying the mcelog be the right approach? How would I go
about testing whether my page offlining algorithm is any good? Would I need
to create my own server?

Sorry for the dumb questions! I'm very new to this!

Thanks,
Ankit

**Comment by andikleen** [comment]
Predictive failure analysis is a big data problem because DIMMs don't fail that often. You would need hundreds or more servers to do any statistically useful analysis.  Even if you determined some new heuristic is better it would be unclear if the same applied to other designs. the 10/24 variant was a reasonable consensus a decade or so ago, but it was always expected that a large site would tune it based on their own analysis of failures.

I'm open to making mcelog configurable for more sophisticated algorithms, but it's unlikely i would change the default. Maybe there could be some mechanism to tune it based on the platform.

**Comment by AnkitSaxena114** [comment]
Got it! Makes sense!

No worries, I don't want to change the default mcelog. Instead, I want to
take the original mcelog, make some modifications for a more
sophisticated page offlining, and be able to test it.

From what I understand, to make the most significant difference in page
offlining, modifications should take place in the page.c file, correct?

I also wanted to get your advice/opinion on how to best test this new page
offlining algorithm. Are there certain server configurations that are best?
Specific CPU/DIMM? Should I follow Download/Installation guidelines
expressed in this link https://mcelog.org/ (the same link from your git
repository). From what I've read, it seems like the mcelog already comes
with the linux distribution so I will have to make sure I already have it.

I think the best first step for me would be to try the default page
offlining (10CE/24hrs) and see if that works. I'm sort of lost on where to
go from there - how will I know if my algorithm works at all?

I'm planning on getting DIMMS with persistent errors rather than injecting
errors when it comes time to test my algorithm.

Again, sorry for the dumb questions! I'm kind of new to this and would love
your feedback!

Thanks again for the help,
Ankit

**Comment by AnkitSaxena114** [comment]
Understood!

I think it makes sense that the threshold was changed from 10ce/24hrs to
2ce/24hrs seeing how most of the time, we see a column type failure. I was
wondering in most modern day data centers if the threshold being used was
10ce/24hrs or 2ce/24hrs?

I also wanted to confirm that to modify/create a page offlining algorithm
the best course of action would be to modify the page.c file in mcelog,
specifically the static int memory_offline(u64 addr) function?

I also want to understand what specifically I should be focusing on , the
linux kernel or mcelog, when it comes to page offlining. When looking at
the linux kernel source code, I read that the policy on WHEN to page
offline would be determined by the userspace (which I assumed to be
mcelog). I thought the mcelog then interfaced with the kernel to apply page
offlining.

Thanks again for all your help! I really appreciate it.

Thanks,
Ankit

**Comment by aegl** [comment]
Ankit,

Correct. “page.c” is where records of previous memory errors are kept. The code in there uses interfacse to the
kenel such as /sys/devices/system/memory/soft_offline_page to ask the kernel to offline a page.

Linux kernel began the process to deprecate mcelog several years ago. The replacement was to be “rasdaemon”.
But that process stalled out for a variety of reasons.

The biggest challenge I see for you to implement some smarter algorithms is not having machine specific details about the errors.
All you get for sure is the system physical address of the error. What you’d really like to have is which DIMM, rank, bank, row, column.
But none of those are generally available.  Nor is there a way to determine which other system addresses are dependent on
specific pieces of h/w (e.g. which other Linux pages share a DIMM row).

-Tony

**Comment by AnkitSaxena114** [comment]
Got it! Thanks for the confirmation.

I think you are right - the challenge is knowing which other linux pages
share the same row. But because of the system address mapping table, we
know how many memory addresses belong to a page and we know that
consecutive pages belong to the same row. This might help a little bit with
row-level page offlining.
But I think page offlining for column fails or bank fails will be very
difficult.

 However I do think whenever there is an error, we know what bank it
belongs to (refer to mcelog.h struct mce).

I really appreciate chiming in!

Thanks for answering my questions and being so helpful,
Ankit

**Comment by AnkitSaxena114** [comment]
Hey guys! quick question - why is the threshold for DIMM offlining
(2CE/24hrs) lower than the threshold for page offlining (10CE/24hrs). I
understand the DIMM threshold used to be 10CE/24hrs before it got  lowered
to 2 CE/24hrs in response to the Intel/Samsung paper.

Based on the thresholds, if a DIMM produces 2CE in 24hrs will the entire
DIMM be offlined? If so, why would the DIMM threshold be lower than the
page threshold? Shouldn't the DIMM have a higher threshold than the page
since it is at a higher level of memory? If a page produces 2 CE wouldn't
the entire DIMM be offlined before the page is? Please let me know where
I'm going wrong!

Thanks,
Ankit

**Comment by aegl** [comment]
Intel and Samsung did a study that showed
2 per 24 hours was best. Look at the git commit
that changed to “2” for URL to study.

Just the 4K page with the problem is taken
offline. Not the whole DIMM.

-Tony
Sent from my iPhone

On Sep 29, 2024, at 05:09, Ankit Saxena ***@***.***> wrote:

﻿

Hey guys! quick question - why is the threshold for DIMM offlining
(2CE/24hrs) lower than the threshold for page offlining (10CE/24hrs). I
understand the DIMM threshold used to be 10CE/24hrs before it got lowered
to 2 CE/24hrs in response to the Intel/Samsung paper.

Based on the thresholds, if a DIMM produces 2CE in 24hrs will the entire
DIMM be offlined? If so, why would the DIMM threshold be lower than the
page threshold? Shouldn't the DIMM have a higher threshold than the page
since it is at a higher level of memory? If a page produces 2 CE wouldn't
the entire DIMM be offlined before the page is? Please let me know where
I'm going wrong!

Thanks,
Ankit

**Comment by AnkitSaxena114** [comment]
Got it!

What's the difference between the socket threshold, DIMM threshold, and
page threshold? From what your describing, it feels like the Page threshold
is the one that should have been changed, not the the DIMM threshold since
only the 4k page is going to be offlined.

On a related note, what does it look like when a page meets its threshold
and what is the consequence? And what does it look like when a socket meets
its threshold and what's the consequence?  In all cases, does a single page
get offlined? If multiple pages contribute to a socket exceeding the
threshold, do they all get offlined?

Also, is it possible for an entire DIMM to be offlined? Socket?

Thanks again for the help,
Ankit

**Comment by ak-intel** [comment]
>What's the difference between the socket threshold, DIMM threshold, and
>page threshold? From what your describing, it feels like the Page threshold
>is the one that should have been changed, not the the DIMM threshold since
>only the 4k page is going to be offlined.

Yes that’s a good point. Tony?

The DIMM ce-error-trigger is just advisory to the administrator, for pages the page error trigger matters.

**Comment by aegl** [comment]
Yes. I messed up and changed the wrong config parameter.

I’ll push a fix.

-Tony

**Comment by AnkitSaxena114** [comment]
Thank guys! Could you also explain what the DIMM threshold and socket
threshold are for?

**Comment by aegl** [comment]
As Andi says below “The DIMM ce-error-trigger is just advisory to the administrator”.

It isn’t practical to take a DIMM offline (typically system physical address space is interleaved
across many DIMMs, so removing one would leave holes throughout the memory).

So the DIMM (and socket) advisories are just to let the admin know where problems are occurring.

-Tony

**Comment by AnkitSaxena114** [comment]
Makes sense!

I had another question about the mce_struct specifically the __u64 synd
value. I've bolded it for your convenience.

/* Fields are zero when not available */
struct mce {
__u64 status;
__u64 misc;
__u64 addr;
__u64 mcgstatus;
__u64 ip;
__u64 tsc; /* cpu time stamp counter */
__u64 time; /* wall time_t when error was detected */
__u8  cpuvendor; /* cpu vendor as encoded in system.h */
__u8  pad1;
__u16 pad2;
__u32 cpuid; /* CPUID 1 EAX */
__u8  cs; /* code segment */
__u8  bank; /* machine check bank */
__u8  cpu; /* cpu number; obsolete; use extcpu now */
__u8  finished;   /* entry is valid */
__u32 extcpu; /* linux cpu number that detected the error */
__u32 socketid; /* CPU socket ID */
__u32 apicid; /* CPU initial apic ID */
__u64 mcgcap; /* MCGCAP MSR: machine check capabilities of CPU */
* __u64 synd; /* MCA_SYND MSR: only valid on SMCA systems */*
__u64 ipid; /* MCA_IPID MSR: only valid on SMCA systems */
__u64 ppin; /* Protected Processor Inventory Number */
__u32 microcode;/* Microcode revision */
__u64 kflags; /* Internal kernel use */
};

Since I'm interested in the DQ and BL values for errors I thought the synd
register would be important. Upon closer examination, it looks like only
SMCA systems would allow me to read the values from the synd register. I
wasn't sure what a SMCA system was originally but it looks like its AMD
only servers. Does that mean I need an AMD processor in my server to decode
the DQ/BL values for each error?

Also, I was reading from the mcelog.org website that AMD stopped supporting
mcelog. I think they are switched over to an infrastructure called EDAC
(Error Detection and Correction).

mcelog does not start on newer AMD systems anymore
AMD stopped supporting mcelog. If you want to use it please contact AMD.
Update: support is being worked on now.

Does this mean even if I had server configuration with an AMD cpu, I still
couldn't use mcelog? And I want to use Mcelog otherwise, I wouldn't be able
to read the __u64 synd?

Thanks again for all the help,
Ankit

**Comment by aegl** [comment]
On Tue, Oct 01, 2024 at 03:30:53PM -0700, Ankit Saxena wrote:
> Makes sense!
>
> I had another question about the mce_struct specifically the __u64 synd
> value. I've bolded it for your convenience.
>
> /* Fields are zero when not available */
> struct mce {
> __u64 status;
> __u64 misc;
> __u64 addr;
> __u64 mcgstatus;
> __u64 ip;
> __u64 tsc; /* cpu time stamp counter */
> __u64 time; /* wall time_t when error was detected */
> __u8  cpuvendor; /* cpu vendor as encoded in system.h */
> __u8  pad1;
> __u16 pad2;
> __u32 cpuid; /* CPUID 1 EAX */
> __u8  cs; /* code segment */
> __u8  bank; /* machine check bank */
> __u8  cpu; /* cpu number; obsolete; use extcpu now */
> __u8  finished;   /* entry is valid */
> __u32 extcpu; /* linux cpu number that detected the error */
> __u32 socketid; /* CPU socket ID */
> __u32 apicid; /* CPU initial apic ID */
> __u64 mcgcap; /* MCGCAP MSR: machine check capabilities of CPU */
> * __u64 synd; /* MCA_SYND MSR: only valid on SMCA systems */*
> __u64 ipid; /* MCA_IPID MSR: only valid on SMCA systems */
> __u64 ppin; /* Protected Processor Inventory Number */
> __u32 microcode;/* Microcode revision */
> __u64 kflags; /* Internal kernel use */
> };
>
> Since I'm interested in the DQ and BL values for errors I thought the synd

What are "DQ" and "BL"?

> register would be important. Upon closer examination, it looks like only
> SMCA systems would allow me to read the values from the synd register. I
> wasn't sure what a SMCA system was originally but it looks like its AMD
> only servers. Does that mean I need an AMD processor in my server to decode
> the DQ/BL values for each error?
>
> Also, I was reading from the mcelog.org website that AMD stopped supporting
> mcelog. I think they are switched over to an infrastructure called EDAC
> (Error Detection and Correction).
>
> mcelog does not start on newer AMD systems anymore
> AMD stopped supporting mcelog. If you want to use it please contact AMD.
> Update: support is being worked on now.
>
> Does this mean even if I had server configuration with an AMD cpu, I still
> couldn't use mcelog? And I want to use Mcelog otherwise, I wouldn't be able
> to read the __u64 synd?

I think AMD provide sufficient information in their machine check
registers to decode errors back to the DIMM.

Intel has a mixed track record. Way back (before Nehalem) there
were moderately good data in machine check banks. Then a big gap
where EDAC drivers poked around into model specific memory
controller registers to decode. Around Cascade Lake Intel
BIOS becan providing an ACPI device specific method to decode
system addresses to the DIMM (and rank/bank/row/column).

-Tony

**Comment by aegl** [comment]
Intel memory controllers don’t expose that level of detail.

**Comment by AnkitSaxena114** [comment]
Hey guys!

I was looking at the mcelog.conf  file and stumbled upon this snippet of
code:

[trigger]
# Maximum number of running triggers
children-max = 2
# execute triggers in this directory
directory = /etc/mcelog

Does this set a limit of 2 concurrent processes (or threads) that can
handle error events triggered by mcelog? If so, how come there aren't more
synchronization  objects like locks, mutexes, or semaphores? Since we have
more than 1 thread, would it make sense to introduce a lock for the
offline_action function in page.c for example? Is it fair to think of a
trigger as a single, unique thread?

I've modified the offline_action function in page.c and I'm worried that
while the offline_action function is being executed, a second page in the
memory will meet the ce threshold and also need offlining. In this case,
would both of the 2 triggers be used? What happens if there is a third page
that meets the ce threshold? Would that third page be forgotten about? Or
will it sit in a queue and wait for the offline action function to finish
executing for the first and second page?

If I wanted to eliminate the chance of any race conditions would I set the
children-max to just one?

Thanks,
Ankit

**Comment by ak-intel** [comment]
>Does this set a limit of 2 concurrent processes (or threads) that can
>handle error events triggered by mcelog?


It’s child processes, not threads.

>If so, how come there aren't more
>synchronization objects like locks, mutexes, or semaphores? Since we have
>more than 1 thread, would it make sense to introduce a lock for the
>offline_action function in page.c for example?

The mcelog daemon by itself is single threaded, it doesn’t need any locking.


> Is it fair to think of a
>trigger as a single, unique thread?

It’s a unique process. Mcelog just fires it off in the background, but doesn’t need to synchronize other than collecting the zombie. The limit is merely to not overwhelm the machine when a flood of errors happens.


>I've modified the offline_action function in page.c and I'm worried that
>while the offline_action function is being executed, a second page in the
>memory will meet the ce threshold and also need offlining. In this case,
>would both of the 2 triggers be used? What happens if there is a third page
>that meets the ce threshold? Would that third page be forgotten about? Or
>will it sit in a queue and wait for the offline action function to finish
>executing for the first and second page?

Mcelog only handles one event at a time. There are no queues for triggers, so if too many would be started some will be head dropped.

**Comment by AnkitSaxena114** [comment]
Got it, thanks!

It's my understanding that when an error takes place, page_account_error
function in page.c gets called and errors gets recorded.Then we check if
the page that the error belongs too, has met the page-ce-threshold. If so,
we call the offline_action function().

I've written some code in the offline_action function. But I'm worried that
while the code is being executed in the offline_action function, other
errors won't get logged and consequently, other pages won't get offlined.
The code that I've written in offline_action relies on the fact that errors
are getting logged and OTHER pages are getting offlined.

Please let me know what you think! I'd love to hear your thoughts and if I
might need to modify my logic in any way!

Thanks again and sorry for all the questions!

Thanks,
Ankit

**Comment by AnkitSaxena114** [comment]
Hi all!  Sorry to bother you again!

I think I just wanted to get confirmation that when offline_action() is
triggered for a page, *mcelog* will not process other errors until it
finishes. Please let me know if it is possible if when offline_action() is
triggered for a page, mcelog will still process other errors concurrently.

Thanks,
Ankit

**Comment by aegl** [comment]
mcelog takes a page offline by writing to "/sys/devices/system/memory/soft_offline_page" (or “hard” version of filename).

I think that write is synchronous. I.e. the Linux kernel doesn’t return from the write until it completes the operation.

So mcelog will block until that page offline is completed. Then pick the next error record from /dev/mcelog to process that.

-Tony

**Comment by AnkitSaxena114** [comment]
Makes sense, I wanted to know your guy's thoughts on designing an
experiment to taste my page offlining algorithm and the necessary steps?

Would I follow the download/installation steps outlined by mcelog -- the
linux hardware error daemon <https://www.mcelog.org/>? Would I be able to
modify the mcelog code, specifically the page.c code to execute my page
offlining algorithm? Will the code, as it is right now, without any of my
modifications compile correctly or will I have to make changes? Are there
any things I should be aware of/look out for?

Any tips/suggestions would be much appreciated! This is going to be sort of
a long term project and I wanted to get your input.

Thanks and sorry for the dumb questions,
Ankit

**Comment by AnkitSaxena114** [comment]
Hey guys,

Another question: I was looking at the kernel source code, trying to find
mcelog. However, I could not find it. Am I looking in the wrong place?  I'm
a little bit confused :)

Thanks,
Ankit

**Comment by aegl** [comment]
> Another question: I was looking at the kernel source code, trying to find
> mcelog. However, I could not find it. Am I looking in the wrong place? I'm
> a little bit confused :)

arch/x86/kernel/cpu/mce/dev-mcelog.c

enabled by CONFIG_X86_MCELOG_LEGACY

-Tony

**Comment by AnkitSaxena114** [comment]
Thanks Tony!

I found the file but I'm looking for the folder I found on GitHub. Since
I'm mostly interested in page offlining, I was hoping to find the page.c
file and the mcelog.conf file.

Are these 2 files as well as the rest of the mcelog folder located
somewhere else? Or are they also in the Linux source code?

Thanks,
Ankit

**Comment by aegl** [comment]
> I found the file but I'm looking for the folder I found on GitHub. Since
> I'm mostly interested in page offlining, I was hoping to find the page.c
> file and the mcelog.conf file.

mcelog is maintained separately from the kernel source.

> Are these 2 files as well as the rest of the mcelog folder located
> somewhere else? Or are they also in the Linux source code?

You’ve already found the github mcelog repository:

                https://github.com/andikleen/mcelog  [1]

you can clone that, make changes, submit pull requests.

-Tony

[1] it’s a alternate repo for https://git.kernel.org/pub/scm/utils/cpu/mce/mcelog.git/

**Comment by AnkitSaxena114** [comment]
Got it!

If I wanted to take the current mcelog, make changes to the page offlining
logic, and test the new page offlining algorithm on my own server (with my
own CPU/DIMMS), would I be able to?

Thanks,
Ankit

**Comment by aegl** [comment]
> If I wanted to take the current mcelog, make changes to the page offlining
> logic, and test the new page offlining algorithm on my own server (with my
> own CPU/DIMMS), would I be able to?

Yes. Just make sure to compile the kernel with:

CONFIG_X86_MCELOG_LEGACY=y
# CONFIG_RAS_CEC is not set

Build your modified mcelog and run it.

The tricky part will be having your system see realistic errors to check your
page offlining algorithm. If you have 100,000+ systems that will happen
naturally due to random bitflips and failing DIMMs.

-Tony

**Comment by AnkitSaxena114** [comment]
Thanks again!

I was wondering if most servers, EDAC and MCElog are running at the same
time? If so, do we need to disable EDAC?

**Comment by aegl** [comment]
> I was wondering if most servers, EDAC and MCElog are running at the same
> time? If so, do we need to disable EDAC?

System administrators generally pick one or the other, though I think its possible to run both at the same time.

-Tony

**Comment by AnkitSaxena114** [comment]
Got it!

I was also wondering if I were to make changes to the page.c file in
mcelog, would I have to recompile the module? Recompile the kernel? I'm
sort of confused about the process of making changes in the mcelog
(specifically the page.c file) and seeing those changes take place on the
hardware. I want to know all the steps I have to take to make the changes I
make in the mcelog file to apply page offlining, actually take place and
physically offline memory addresses in the dram.

Thanks,
Ankit

**Comment by AnkitSaxena114** [comment]
Hey team,

I had a couple questions I could hope you could help me with:

1) What is the difference between MCE vs MCA?
2) Are errors detected by patrol scrub reported to the OS? If so, are they
recognized by mcelog? If so, are they being page offlined?

Thanks,
Ankit

**Comment by aegl** [comment]
1.  MCE = Machine Check Exception (also known as #MC or  INT#18)

MCA = Machine Check Architecture … the whol CPU feature for detecting and reporting errors.

It’s not uncommon for people to mix them up and use the wrong one in various contexts.


  1.  The h/w patrol scrubber does report errors. Single bit errors are fixed up by writing the corrected data back to DIMMs. Signature in the MCi_STATUS register will have UC=0. Error signaled with CMCI (if enabled,)

Uncorrected errors are reported with MCi_STATUS UC=1. Old CPUs (before Icelake generation) signal with a #MC. Icelake and newer signal with CMCI.

Logs are passed to mcelog which may offline the page for corrected errors if the threshold is reached.



-Tony

**Comment by AnkitSaxena114** [comment]
Hey Tony,

Really appreciate you getting back to me! I have 2 new questions for you!

1) I'm sort of confused by MCE. It seems like from everything I've read,
MCE is for *UE*. But in the* page.c* file in the function
*account_page_error(struct
mce *m, int channel, int dimm)* , when a MCE is detected, the *CE *leaky
bucket is incremented. Please let me know if my understanding is correct or
if I'm missing something about what MCE is.

2) Since CMCI is the new signal, Is MCE no longer used to signal errors?
Standard Uncorrectable errors, uncorrectable errors with no action,
uncorrectable errors with software action optional, uncorrectable errors
with software action required, and correctable errors are all signalled via
CMCI?

Thanks,
Ankit

**Comment by aegl** [comment]
Ankit,

account_page_error() is Andi’s code. I don’t have time just now to dig through it to see what it is doing.

Machine check architecture has two ways to *signal* errors.

  1.  #MC – this is only used for uncorrected errors.
  2.  CMCI – older CPUs only use this for corrected errors, but starting with Icelake it is also use for uncorrected errors that are not associated with the currently executing instruction (e.g. the memory controllers background scan of DIMMs).

Older CPUs use #MC for the SRAO (action optional) signature errors. Icelake and newer use a UCNA signature and signal with CMCI.

SRAR (action required) is signaled with #MC (on newer CPUs with local machine check just to the logical CPU affected).

Fatal errors are signaled with a broadcast #MC to all logical CPUs.

-Tony

**Comment by andikleen** [comment]
On Mon, Dec 02, 2024 at 09:48:25AM -0800, Tony Luck wrote:
> Ankit,
> 
> account_page_error() is Andi’s code. I don’t have time just now to dig through
> it to see what it is doing.

mcelog doesn't know the difference between MCE and CMCI, it's all just
errors out of /dev/mcelog. So the functions are all the same.

-Andi

**Comment by AnkitSaxena114** [comment]
Hey team,

Hope you had a good weekend!

In my page offlining experiment, I'm noticing 2 contradicting results. When I inspect /proc/meminfo I can see the HardwareCorrupted kB count increase to what it should be based on the algorithm I wrote 😊. However, when I execute "mcelog--client", I get "offline-failed triggered", instead of "offline triggered" for each page that initially met the CE/24hr threshold☹. It's hard for me to know if pages are actually getting offlined when mcelog is telling me that the offlining failed but the kernel seems to be showing me that pages are getting offlined.

I'm curious if it has anything to do with the number of pages I'm offlining? If I were to offline a million pages or about 4,000,000 kB of memory, as I do in one of my tests, will mcelog not be able to handle that amount of volume. I'm noticing that when I offline a million pages after a single error, not all million pages are offlined in an instant. Every second, about a thousand pages get's offlined until the total million pages have been offlined.

Sorry for the trouble and thanks for all the help,
Ankit

**Comment by AnkitSaxena114** [comment]
BTW, this is how it looks like on my end:

mcelog –client:
***@***.***

/proc/meminfo:
***@***.***


As you can see, Mcelog – client is showing that the offline failed but the kernel is showing me that ~4,000,000 kB has been offlined, or around 1,000,000 pages. Please let me know if there is something wrong on my end or if there’s anything I can do to resolve this issue if pages are actually not getting offlined!

Thanks,
Ankit


From: Ankit Saxena
Sent: Monday, December 16, 2024 12:32 PM
To: 'andikleen/mcelog' ***@***.***>
Cc: 'andikleen/mcelog' ***@***.***>; Jong Min Lee ***@***.***>; Michael Sporer ***@***.***>; ***@***.***' ***@***.***>
Subject: Page Offlining Experiment

Hey team,

Hope you had a good weekend!

In my page offlining experiment, I'm noticing 2 contradicting results. When I inspect /proc/meminfo I can see the HardwareCorrupted kB count increase to what it should be based on the algorithm I wrote 😊. However, when I execute "mcelog--client", I get "offline-failed triggered", instead of "offline triggered" for each page that initially met the CE/24hr threshold☹. It's hard for me to know if pages are actually getting offlined when mcelog is telling me that the offlining failed but the kernel seems to be showing me that pages are getting offlined.

I'm curious if it has anything to do with the number of pages I'm offlining? If I were to offline a million pages or about 4,000,000 kB of memory, as I do in one of my tests, will mcelog not be able to handle that amount of volume. I'm noticing that when I offline a million pages after a single error, not all million pages are offlined in an instant. Every second, about a thousand pages get's offlined until the total million pages have been offlined.

Sorry for the trouble and thanks for all the help,
Ankit

**Comment by aegl** [comment]
Something is “censoring” test that looks like e-mail addresses in your messages.

The communications path from kernel to the mcelog daemon via /dev/mcelog has small capacity. Used to be a fixed 32-element buffer, but kernels v5.7 and newer allocate a larger buffer based on the number of CPUs.

See kernel commit:

d8ecca4043f2 ("x86/mce/dev-mcelog: Dynamically allocate space for machine check records")

I expect this buffer is resulting in loss of error records to mcelog when you do large scale page offline tests.
If this is happening, you should see messages in mcelog output that say “Warning: MCE buffer is overflowed.”

-Tony

**Comment by andikleen** [comment]
Offlining shouldn't generate new mcelog messages.

In general you cannot offline very large areas in a normal kernel
because they might contain kernel structures that cannot be moved. 
There is something like the movable zone that can be configured to
avoid putting kernel structures into specific regions, but it cannot
cover all.

**Comment by AnkitSaxena114** [comment]
Thanks guys!

I really appreciate the information!

I tried stress testing and offlining 2^14 or 16,384 pages after every error
and every offlining attempt seemed to be successful. I'm guess that's the
upper limit because I tried 2^15 and the offlining failed.

I just had a question about kernel structures in general - does the server
allocated a fixed amount of memory for the kernel? and for the userspace?
or does it vary?

Thanks,
Ankit

**Comment by andikleen** [comment]
On Fri, Dec 20, 2024 at 05:49:14PM -0800, Ankit Saxena wrote:
> Thanks guys!
> 
> I really appreciate the information!
> 
> I tried stress testing and offlining 2^14 or 16,384 pages after every error
> and every offlining attempt seemed to be successful. I'm guess that's the
> upper limit because I tried 2^15 and the offlining failed.

It will depend on many factors.
> 
> I just had a question about kernel structures in general - does the server
> allocated a fixed amount of memory for the kernel? and for the userspace?
> or does it vary?

It varies.

**Comment by AnkitSaxena114** [comment]
It looks like it really does vary!

Today, I tried offlining 2^11 or 2048 pages per error and got mixed
results. It was an overnight stress test and for some pages, the offlining
was triggered and for other pages the offlining failed. I was wondering why
that is?

**Pull request closed without merging**
